### ISSUE TITLE
При добавлении одной игры ответ false в методе boolean containsGame.

### ISSUE THREAD

**Issue by Pavelll23** [Pavelll23/GamingActivity#1]
# Описание
Если  добавлять только одну игру, то игра не будет добавлена.

# Локация дефекта
  https://github.com/Pavelll23/GamingActivity/blob/c9e39cd83a1f3ba0ec6608655a369ecee1c6c006/src/main/java/ru/netology/GameStore.java#L51

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Pavelll23/GamingActivity/blob/c9e39cd83a1f3ba0ec6608655a369ecee1c6c006/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2. Выставить значение в переменную game (Нетология Батл, Аркады)
3. Запустить тест
4. Посмотреть на вывод в консоли

*Ожидаемый результат.*Вывод в консоли true
*Фактический результат.*Вывод в консоли false

# Скриншот
![Games – GameStoreTest java 2023-02-21 22 13 04](https://user-images.githubusercontent.com/116386264/220437810-edac1c4e-2969-4a0b-8d28-f584e8c1e38b.png)

# Окружение
* **Операционная система.**Windows 10 версия 21H2
* **IDE:**Intellij IDEA 2022.2.3
* **JAVA.**JDK:corretto-11

@victor-balandin

**Comment by victor-balandin** [comment]
Баг отработан, внесены изменения в код
