### ISSUE TITLE
Не суммирует время игры в методе add PlayTime

### ISSUE THREAD

**Issue by Pavelll23** [Pavelll23/GamingActivity#2]
# Описание
При игре одним игроком в игру одного и того каталога, общее время игры не увеличивается.

# Локация дефекта
https://github.com/Pavelll23/GamingActivity/blob/c9e39cd83a1f3ba0ec6608655a369ecee1c6c006/src/main/java/ru/netology/GameStore.java#L66

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Pavelll23/GamingActivity/blob/c9e39cd83a1f3ba0ec6608655a369ecee1c6c006/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2. Выставить значение в переменную store(Vova, 5)
3. Выставить значение в переменную store(Vova, 3)
4. Запустить тест
5. Посмотреть на вывод в консоли

*Ожидаемый результат.*Вывод сообщения в консоли: Vova = 8
*Фактический результат.*Вывод сообщения в консоли: Vova = 5

# Скриншот
![Games – GameStoreTest java 2023-02-21 22 59 58](https://user-images.githubusercontent.com/116386264/220446292-042863c6-a97b-4dcf-afab-75ec40e69b34.png)

# Окружение
* **Операционная система.**Windows 10 версия 21H2
* **IDE.**Intellij IDEA 2022.2.3
* **Java:**JDK:corretto-11

**Comment by victor-balandin** [comment]
Баг отработан, внесены изменения в код
