### ISSUE TITLE
В методе getMostPlayer программа не ищет имя игрока если у него наигран один час

### ISSUE THREAD

**Issue by Pavelll23** [Pavelll23/GamingActivity#3]
# Описание
Если у игрока время игры меньше двух часов, то программа выдает, что игроков игравших в игру нет

# Локация дефекта
https://github.com/Pavelll23/GamingActivity/blob/c9e39cd83a1f3ba0ec6608655a369ecee1c6c006/src/main/java/ru/netology/GameStore.java#L81

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Pavelll23/GamingActivity/blob/c9e39cd83a1f3ba0ec6608655a369ecee1c6c006/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2.  В тесте shouldMostPlayerIfOneHouer выставить значение переменной storre (Vova, 1)
3. Запустить тест
4. Посмотреть на вывод в консоли

*Ожидаемый результат.*Вывод сообщения в консоли: Vova
*Фактический результат.*Вывод сообщения в консоли: null

# Скриншот
![Games – GameStoreTest java 2023-02-21 23 31 49](https://user-images.githubusercontent.com/116386264/220451924-229a52a7-8e0a-43b3-986c-5d59b3a8d7be.png)

# Окружение
* **Операционная система.**Windows 10 версия 21Н2
* **IDE:**Intellij IDEA 2022.2.3
* **Java:**JDK:corretto-11

**Comment by victor-balandin** [comment]
Баг отработан, внесены изменения в код
