### ISSUE TITLE
Отсутствует возможность обратиться к Мар класса Player

### ISSUE THREAD

**Issue by victor-balandin** [Pavelll23/GamingActivity#4]
# Описание
Мар игрока с доступом private. Отсутствует возможность обратиться к нему для тестирования корректности внесения данных.

# Локация дефекта
https://github.com/Pavelll23/GamingActivity/blob/46438638decfb38926134f4fc789534604adab04/src/main/java/ru/netology/Player.java#L12

# Шаги воспроизведения
1. Запускаем тест на добавление игры игроку shouldTestInstallGame
2. Получить вывод консоли

*Ожидаемый результат:*  вывод в консоли данных из listPlayers с параметрами (game, 0)
*Фактический результат:* вывод в консоли ошибки playedTime has private access in ru.netology.Player

# Скриншот
<img width="1440" alt="Снимок экрана 2023-02-22 в 12 34 27" src="https://user-images.githubusercontent.com/118800501/220584339-3c819929-d234-423b-aefc-955021df1498.png">

# Окружение
* **Операционная система:** macOS 13.0.1 (22A400) 
* **IDE:** IntelliJ IDEA 2022.3 (Community Edition) 
* **Java:** OpenJDK 11

**Comment by Pavelll23** [comment]
Были внесены правки в код
