### ISSUE TITLE
При отсутствие установленной игроку игры и запуске метода play отсутствует ошибка RuntimeException

### ISSUE THREAD

**Issue by victor-balandin** [Pavelll23/GamingActivity#5]
# Описание
Согласно условию, при отсутствии установленной игры и запуска метода play, должна вылетать ошибка RuntimeException, чего не приходит

# Локализация 
https://github.com/Pavelll23/GamingActivity/blob/46438638decfb38926134f4fc789534604adab04/src/main/java/ru/netology/Player.java#L33

# Шаги воспроизведения
1. В классе PlayerTest находим тест testPlayIfGameNotInstall
2. Запускаем тест
3. Смотрим вывод консоли

*Ожидаемый результат:* Тест проходит
*Фактический результат:* Тест не проходит, ошибка Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот
<img width="1440" alt="Снимок экрана 2023-02-22 в 13 02 38" src="https://user-images.githubusercontent.com/118800501/220592914-a7f37e39-0728-45e2-8e8a-8774afa4b11e.png">

# Окружение
* **Операционная система:** macOS 13.0.1 (22A400) 
* **IDE:** IntelliJ IDEA 2022.3 (Community Edition) 
* **Java:** OpenJDK 11

**Comment by Pavelll23** [comment]
Были внесены правки в метод  play
