### ISSUE TITLE
Метод play класса Player не передает в Мар игрока данные по количеству часов, сыгранных в игру

### ISSUE THREAD

**Issue by victor-balandin** [Pavelll23/GamingActivity#6]
# Описание
Метод play должен передавать данные об игре и количестве часов в нее сыгранных в Мар класса Player. Данные об игре передаются, а о количестве часов нет
# Локация дефекта
https://github.com/Pavelll23/GamingActivity/blob/46438638decfb38926134f4fc789534604adab04/src/main/java/ru/netology/Player.java#L36

# Шаги воспроизведения
1. Запускаем тест shouldTestPlayInPlayerMap в режиме Debug  на добавление игры и количества времени в Мар игрока shouldTestPlayInPlayerMap
2. Поставить точку в строке  player.play(game, 3);
3. Посмотреть вывод в консоли

*Ожидаемый результат:* В Мар добавлен ключ указанной игры, value = 3
*Фактический результат:* Ключ добавлен, value = 0

# Скриншот
<img width="1440" alt="Снимок экрана 2023-02-22 в 13 23 19" src="https://user-images.githubusercontent.com/118800501/220592662-65031007-6029-458b-b0b2-189ce530d725.png">

# Окружение
* **Операционная система:** macOS 13.0.1 (22A400) 
* **IDE:** IntelliJ IDEA 2022.3 (Community Edition) 
* **Java:** OpenJDK 11

**Comment by Pavelll23** [comment]
Были внесены правки в метод  play
