### ISSUE TITLE
Метод sumGenre не суммирует время, проигранное во все игры этого жанра этим игроком, в том числе, если игра одна

### ISSUE THREAD

**Issue by victor-balandin** [Pavelll23/GamingActivity#7]
# Описание
Суть метода sumGenre - суммировать время, проигранное во все игры этого жанра этим игроком, принимая значение жанра на вход. В случае, если игра одна или их несколько, суммирование не происходит

# Локация дефекта
https://github.com/Pavelll23/GamingActivity/blob/46438638decfb38926134f4fc789534604adab04/src/main/java/ru/netology/Player.java#L47

# Шаги воспроизведения
1. Запускаем тест shouldSumGenreIfOneGame, рассматриваем случай с одной игрой
2. Смотрим вывод консоли
3. Запускаем тест shouldSumGenreIfSomeGames, рассматриваем случай с несколькими играми одного жанра
4. Смотрим вывод консоли

*Ожидаемый результат:*  Тесты проходят с указанными в них значениями
*Фактический результат:* В первом и втором случае результат суммирования 0

# Скриншоты
<img width="1440" alt="Снимок экрана 2023-02-22 в 13 32 57" src="https://user-images.githubusercontent.com/118800501/220594887-3d18fd6a-f0bd-471d-aede-9682591c0feb.png">
<img width="1440" alt="Снимок экрана 2023-02-22 в 13 33 44" src="https://user-images.githubusercontent.com/118800501/220595041-8517d940-7935-4787-a42f-cabdc5944840.png">
консоли

# Окружение
* **Операционная система:** macOS 13.0.1 (22A400) 
* **IDE:** IntelliJ IDEA 2022.3 (Community Edition) 
* **Java:** OpenJDK 11

**Comment by Pavelll23** [comment]
Были внесены правки в метод  sumGenre
