### ISSUE TITLE
Метод mostPlayerByGenre не возвращает игру этого жанра , который получил на вход, в которую играли больше всего

### ISSUE THREAD

**Issue by victor-balandin** [Pavelll23/GamingActivity#8]
# Описание
Метод mostPlayerByGenre должен при обращении возвращать игру из указанного жанра, в которую играли больше всего

# Локация дефекта
https://github.com/Pavelll23/GamingActivity/blob/46438638decfb38926134f4fc789534604adab04/src/main/java/ru/netology/Player.java#L59

# Шаги воспроизведения
1. Запускаем тест     public void shouldTestMostPlayerByGenre()
2. Смотрим вывод консоли

*Ожидаемый результат:*  Тест проходит с указанными в тесте параметрами
*Фактический результат:* Возвращается null

# Скриншот
<img width="1440" alt="Снимок экрана 2023-02-22 в 13 38 56" src="https://user-images.githubusercontent.com/118800501/220596237-34112b7b-e167-4d65-9feb-c6afcbcefb3e.png">

# Окружение
* **Операционная система:** macOS 13.0.1 (22A400) 
* **IDE:** IntelliJ IDEA 2022.3 (Community Edition) 
* **Java:** OpenJDK 11

**Comment by Pavelll23** [comment]
Был дописан код метода  mostPlayerByGenre
