### ISSUE TITLE
Возвращает 0 в методе getSumPlayedTime при любых вводных параметрах

### ISSUE THREAD

**Issue by Pavelll23** [Pavelll23/GamingActivity#9]
# Описание
По окончании работы программы все время выдает 0, какие бы параметры не вводились

# Локация дефекта
https://github.com/Pavelll23/GamingActivity/blob/16108a00851eba2e8fd674291472b2027f8e78be/src/main/java/ru/netology/GameStore.java#L93

# Шаги воспроизведения
1. Открыть[код программы]https://github.com/Pavelll23/GamingActivity/blob/16108a00851eba2e8fd674291472b2027f8e78be/src/test/java/ru/netology/GameStoreTest.java в IDEA
2. Выставить параметры
3. Запустить тест shouldSumPlayedTime
4. Посмотреть на вывод в консоли

*Ожидаемый результат:*В консоли отображается 18
*Фактический результат:*В консоли отображается 0

# Скриншот
![Games – GameStoreTest java 2023-02-22 23 28 11](https://user-images.githubusercontent.com/116386264/220751355-bcc3f271-3f95-44a8-a2c3-6a832081c355.png)

# Окружение
* **Операционная система**Windows 10 версия 21Н2
* **IDE:**Intellij IDEA 2022.2.3
* **Java:**JDKcorretto-11

**Comment by victor-balandin** [comment]
Баг отработан, внесены изменения в код
